-- Query 1: Orders with customer and product

SELECT o.order_id, c.customer_city, p.product_name, o.order_amount
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN products p ON o.product_id = p.product_id;

-- Query 2: Total revenue

SELECT SUM(order_amount) AS total_revenue FROM orders;

-- Query 3: Average order value per city

SELECT c.customer_city, AVG(order_amount) AS avg_order_amount
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_city;

-- Query 4: Orders per product

SELECT p.product_name, COUNT(*) AS total_orders
FROM orders o
JOIN products p ON o.product_id = p.product_id
GROUP BY p.product_name;

-- Query 5: Create view (drop if exists first)

DROP VIEW IF EXISTS order_summary;

CREATE VIEW order_summary AS
SELECT o.order_id, c.customer_city, p.product_name, o.order_date, o.order_amount
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN products p ON o.product_id = p.product_id;

--Query 6: List all customers who placed more than one order

SELECT customer_id, COUNT(order_id) AS total_orders
FROM orders
GROUP BY customer_id
HAVING COUNT(order_id) > 1;

--Query 7: Top 3 cities by total revenue

SELECT c.customer_city, SUM(o.order_amount) AS city_revenue
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_city
ORDER BY city_revenue DESC
LIMIT 3;

--Query 8: Total revenue generated by each product

SELECT p.product_name, SUM(o.order_amount) AS total_revenue
FROM orders o
JOIN products p ON o.product_id = p.product_id
GROUP BY p.product_name;